name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */10 * * *' # Runs every 10 hours
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Keep-alive commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Keep-alive: Reseting Streamlit hibernation timer"
          git push
